### ISSUE TITLE
bordes desiguales de las cards dependiendo del largo del nombre de la receta

### ISSUE THREAD

**Issue by wayusei** [wayusei/find-a-meal#9]
¿Se podrá controlar un largo estándar de la tarjeta que contemple el breakdown del nombre de la receta para que no queden disparejos las cards?
![image](https://user-images.githubusercontent.com/6761758/187752939-e5b6d452-9498-4df1-84d8-a78597d08843.png)

**Comment by veronicaenro** [comment]
Se resolvió issue
